language: generic 
sudo: required
services:
 - docker

before_install:
 - docker build -t devopslapa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true devopslapa/docker-react npm run test


